# Generated by Django 2.2.5 on 2020-01-14 08:19

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='company email')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('company_tin', models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')])),
                ('company_status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'SMSUsers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SMSPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_price', models.FloatField(max_length=25)),
                ('price_desc', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', related_query_name='SMSPrices', to='commons.Type')),
            ],
            options={
                'verbose_name_plural': 'SMSPrices',
            },
        ),
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_number_to', models.CharField(max_length=14)),
                ('sms_content', models.CharField(max_length=160)),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('delivery_status', models.BooleanField(default=False)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_that_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SMSMessages',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_created', models.DateTimeField(auto_now=True)),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_user', related_query_name='invoiced_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='smsuser',
            name='sms_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sms_prices', to='commons.SMSPrice'),
        ),
        migrations.AddField(
            model_name='smsuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
