# Generated by Django 2.2.5 on 2019-09-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprice',
            options={'verbose_name': 'SMSPrices'},
        ),
        migrations.AlterField(
            model_name='smsprice',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='types', to='commons.Type'),
        ),
        migrations.AlterField(
            model_name='smsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='company email'),
        ),
        migrations.AlterField(
            model_name='smsuser',
            name='sms_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sms_prices', to='commons.SMSPrice'),
        ),
    ]
