# Generated by Django 2.2.5 on 2020-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprice',
            name='price_desc',
            field=models.CharField(max_length=100),
        ),
    ]
