# Generated by Django 2.2.5 on 2019-09-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20190922_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprice',
            options={'verbose_name_plural': 'SMSPrices'},
        ),
        migrations.AlterModelOptions(
            name='smsuser',
            options={'verbose_name_plural': 'SMSUsers'},
        ),
    ]
