# Generated by Django 2.2.5 on 2019-09-28 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_auto_20190922_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', related_query_name='SMSPrices', to='commons.Type'),
        ),
        migrations.AlterField(
            model_name='smsuser',
            name='sms_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_prices', to='commons.SMSPrice'),
        ),
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_number_to', models.CharField(max_length=14)),
                ('sms_content', models.CharField(max_length=160)),
                ('sender_company', models.ForeignKey(limit_choices_to=1, on_delete=django.db.models.deletion.PROTECT, related_name='SenderUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
