# Generated by Django 2.2.5 on 2019-09-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_added_smsmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsmessages',
            options={'verbose_name_plural': 'SMSMessages'},
        ),
    ]
