# Generated by Django 2.2.5 on 2019-09-30 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_auto_20190930_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessages',
            name='sender_company',
            field=models.ForeignKey(limit_choices_to=1, on_delete=django.db.models.deletion.PROTECT, related_name='company_that_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
