# Generated by Django 2.2.5 on 2019-10-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_modified_SMSMessages_sender_company_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessages',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsmessages',
            name='sent_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
