# Generated by Django 2.2.5 on 2019-10-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_auto_20191003_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessages',
            old_name='sender_company',
            new_name='sending_user',
        ),
    ]
