# Generated by Django 2.2.5 on 2019-10-05 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_renamed_sender_company_field_to_sending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessages',
            name='sending_user',
            field=models.ForeignKey(limit_choices_to=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_that_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
