# Generated by Django 2.2.5 on 2019-10-05 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_renamed_sending_user_related_name_to_user_that_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessages',
            name='sending_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_that_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
