# Generated by Django 2.2.5 on 2019-10-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0010_removed_limit_choices_from_sending_user_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsuser',
            name='sms_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sms_prices', to='commons.SMSPrice'),
        ),
    ]
