# Generated by Django 2.2.5 on 2019-12-07 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0011_add_sms_price_default_value_to_smsusers_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsuser',
            name='company_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smsuser',
            name='company_tin',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')]),
        ),
    ]
