# Generated by Django 2.2.5 on 2019-12-07 00:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0012_auto_20191207_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')])),
                ('payment_status', models.BooleanField(default=False)),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_customer', related_query_name='invoiced_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
