# Generated by Django 2.2.5 on 2019-12-07 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0013_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'Invoices'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')]),
        ),
    ]
