# Generated by Django 2.2.5 on 2019-12-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0014_auto_20191207_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_company', related_query_name='invoiced_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
