# Generated by Django 2.2.5 on 2019-12-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0016_auto_20191213_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessages',
            name='sending_company',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
