# Generated by Django 2.2.5 on 2019-12-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0017_smsmessages_sending_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessages',
            name='sending_company',
        ),
    ]
