# Generated by Django 2.2.5 on 2019-12-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0018_remove_smsmessages_sending_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
