# Generated by Django 2.2.5 on 2019-12-15 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0019_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(default=1, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')])),
                ('payment_status', models.BooleanField(default=False)),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_user', related_query_name='invoiced_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
