# Generated by Django 2.2.5 on 2019-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0020_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
