# Generated by Django 2.2.5 on 2019-12-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0021_auto_20191215_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
