# Generated by Django 2.2.5 on 2019-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0023_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprice',
            name='set_price',
            field=models.FloatField(max_length=25),
        ),
    ]
