# Generated by Django 2.2.5 on 2020-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0025_invoice_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
