# Generated by Django 2.2.11 on 2020-07-29 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0026_invoice_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsuser',
            name='company_phone',
            field=models.CharField(default='000000', max_length=14),
        ),
        migrations.AlterField(
            model_name='smsmessages',
            name='sent_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 29, 13, 46, 6, 915939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='smsuser',
            name='company_status',
            field=models.BooleanField(default=False),
        ),
    ]
