# Generated by Django 2.2.5 on 2021-06-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20200207_0935'),
        ('commons', '0027_auto_20200729_1346'),
    ]

    operations = [
    ]
